<style>


  a {text-decoration: none;}
  a:link { text-decoration: none;}
  a:visited { text-decoration: none;}
  a:hover { text-decoration: underline;}

  h1{font-size:16px;font-family:verdana}
  sub{font-size:10px;font-family:verdana}
  span{font-size:12px;font-family:verdana}
  th{
  padding-left:3px;
  padding-right:3px;
  border-width: 1px;
  border-style: solid;
  border-color: #5373A2;
  font-family:verdana;
  font-size:13px;
  }

  .tdc{
  padding:3px;
  border-width: 1px;
  border-style: solid;
  border-color: #5373A2;
  font-family:verdana;
  font-size:11px;
  }

  .tdo{
  padding:3px;
  font-family:verdana;
  font-size:11px;
  }

  .tbl_1{
  border-spacing: 2px;
  border-collapse: collapse;
  background-color: white;
  }

  .bodytxt
  {
  font-weight: normal;
  font-size: 11px;
  color: #333333;
  line-height: normal;
  font-family: Verdana, Arial, Helvetica, sans-serif;
  }



  .td_label{font-family: Verdana, Arial, Helvetica, sans-serif;font-size:10px;color:#5F7AFC;font-weight:bold;text-align:right}
  div#preload{font-family: Verdana, Arial, Helvetica, sans-serif;font-size:10px;color:#5F7AFC;font-weight:bold}
  div#trends {position:absolute;width:1010px;height:560px;top:40px;left:5px;background-color:white;z-index:1;border-width:1px;border-style:solid;border-color:#CBD6E4;text-align:left;visibility:visible;overflow:auto;}
  div#below {position:absolute;width:700px;height:100px;top:370px;left:250px;background-color:white;z-index:1;border-width:1px;border-style:solid;border-color:#5F7AFC;text-align:center}
  div#footnote{font-family: Verdana, Arial, Helvetica, sans-serif;font-size:8px;color:#CBD6E4;text-align:right}

  .FormDropdown
  {
  font-family: Verdana, Arial, Helvetica, sans-serif;
  font-size: 12px;
  color:#5F7AFC;
  width: 40px;
  border-width: 1px;
  border-style: solid;
  border-color: #CBD6E4;
  }

  .inputStyle
  {
  border-width: 1px;
  border-style: solid;
  border-color: #5F7AFC;
  text-align:center;
  font-family: Verdana;
  font-size: 10pt;
  color: #3952F9;
  height: 20px;
  }



  .submission_box{position:absolute;top:11px;left:700px;cursor:pointer}
  .saveexcel_box{position:absolute;top:11px;left:760px;cursor:pointer}
  .print_box{position:absolute;top:11px;left:840px;cursor:pointer}

  .report_select {position:absolute;top:4px;left:530px;}
  .report_select .title {position:absolute;top:4px;left:7px;font-family: Verdana, Arial, Helvetica, sans-serif;font-size:10px;color:#5F7AFC;font-weight:bold;text-align:right;}
  .report_select .left_arrow {position:absolute;top:6px;left:54px;cursor:pointer;}
  .report_select .right_arrow {position:absolute;top:6px;left:245px;cursor:pointer;}
  .report_select .box
  {
  position:absolute;
  top:0px;
  left:65px;
  border-width: 1px;
  border-style: solid;
  border-color: #5F7AFC;
  text-align:center;
  font-family: Verdana;
  font-size: 10pt;
  font-weight: bold;
  color: #3952F9;
  width:170px;
  height: 18px;
  }

  .date_select {position:absolute;top:10px;left:320px;}
  .date_select .title {position:absolute;width:85px;top:2px;left:0px;font-family: Verdana, Arial, Helvetica, sans-serif;font-size:10px;color:#5F7AFC;font-weight:bold;text-align:right;}
  .date_select .cal {position:absolute;top:2px;left:195px;cursor:pointer;}
  .date_select .box
  {
  position:absolute;
  top:0px;
  left:90px;
  border-width: 1px;
  border-style: solid;
  border-color: #5F7AFC;
  text-align:center;
  font-family: Verdana;
  font-size: 10pt;
  font-weight: bold;
  color: #3952F9;
  width:100px;
  height: 18px;
  }
  .dist_select {position:absolute;top:10px;left:220px;}
  .dist_select .title {position:absolute;width:85px;top:2px;left:50px;font-family: Verdana, Arial, Helvetica, sans-serif;font-size:10px;color:#5F7AFC;font-weight:bold;text-align:right;}

  .dist_select .Dropdown
  {
  position:absolute;
  top:0px;
  left:140px;
  border-width: 0px;
  border-style: solid;
  border-color: #5F7AFC;
  text-align:center;
  font-family: Verdana;
  font-size: 8pt;
  font-weight: bold;
  color: #3952F9;
  width:130px;
  height: 18px;
  }

  
    






</style>